CREATE DATABASE IF NOT EXISTS DUTY_ROSTER;
USE DUTY_ROSTER;

CREATE TABLE IF NOT EXISTS MEMBER (
	ID INT,
	NAME VARCHAR(255),
	ADDRESS VARCHAR(255),
	PHONE_NUMBER VARCHAR(20),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS DUTY (
	ID INT,
	NAME VARCHAR(255),
	DESCRIPTION VARCHAR(1024),
	PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS ALLOCATION (
	MEMBER_ID INT,
	DUTY_ID INT,
	ALLOCATION_START_DATETIME DATETIME,
	ALLOCATION_END_DATETIME DATETIME,
	FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (ID),
	FOREIGN KEY (DUTY_ID) REFERENCES DUTY (ID)
);